version: 2.1
orbs:
  node: circleci/node@1.1.6
  serverless: circleci/serverless-framework@1.0.1
executors:
  node-env:
    docker:
      - image: circleci/node:latest
workflows:
  main:
    jobs: 
      - build:
          context: 'Anubis'
jobs:
  build:
    executor: node-env
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - serverless/setup:
          app-name: anubis-web
          org-name: anubis
      - run: serverless deploy